
nosana:
  description: Nosana x Squads Deployment

global:
  image: nosana/solana:v1.0.5

  environment:
    SOLANA_URL: devnet # testnet / devnet / mainnet / <your-custom-sol-rpc>
    PROGRAM_ID: Avrqn8UZa2EeGMHt9N7sDsxGcHTcWGYuWu8EXcyN3tv1

  trigger:
    branch:
      - master

jobs:
#  - name: build program
#    commands:
#      - npm run build:program-rust
#    artifacts:
#      - name: program
#        path: dist/program/helloworld.so
  - name: verify hash
    image: ubuntu:latest
    commands:
      - ldd --version
          
  - name: verify hash
    image: ellipsislabs/solana:latest
    commands:
      - ldd --version
      - curl -sSf https://raw.githubusercontent.com/Ellipsis-Labs/solana-verifiable-build/master/verifier-cli-install.sh | bash
      - PROGRAM_HASH = $(/root/bin/solana-verify get-program-hash $PROGRAM_ID)
      - echo $PROGRAM_HASH
#      - SO_HASH = $(solana-verify get-executable-hash /dist/program/helloworld.so)
#      - test $PROGRAM_HASH = $SO_HASH
#    resources:
#      - name: program
#        path: /