
nosana:
  description: Nosana x Squads Deployment

global:
  image: nosana/solana:v1.0.5

  environment:
    SOLANA_URL: devnet # testnet / devnet / mainnet / <your-custom-sol-rpc>
    PROGRAM_ID: Avrqn8UZa2EeGMHt9N7sDsxGcHTcWGYuWu8EXcyN3tv1

  trigger:
    branch:
      - master

jobs:
  - name: build program
    commands:
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program/helloworld.so
  - name: test
    commands:
      - solana config set --url $SOLANA_URL
      - solana config get
      - cat ~/.config/solana/cli/config.yml
    artifacts:
      - name: config
        path: /root/.config
  - name: verify hash
    image: ubuntu:latest
    commands:
      - ldd --version
      - apt-get -y install curl
      - curl -sSf https://raw.githubusercontent.com/Ellipsis-Labs/solana-verifiable-build/master/verifier-cli-install.sh | bash
      - /root/bin/solana-verify get-program-hash $PROGRAM_ID > program_hash.txt
      - /root/bin/solana-verify get-executable-hash /dist/program/helloworld.so > executable_hash.txt
      - test $(cat program_hash.txt) = $(cat executable_hash.txt)
    resources:
      - name: config
        path: /
      - name: program
        path: /    